fmt

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,149 +2,108 @@
 # Tagging a commit with [circle full] will build everything.
 version: 2
 jobs:
-    build_docs:
-      docker:
-        - image: cimg/python:3.10
-      resource_class: medium
-      steps:
-        - checkout
-        - run:
-            name: Set BASH_ENV
-            command: |
-              echo "set -e" >> $BASH_ENV
-              echo "export DISPLAY=:99" >> $BASH_ENV
-              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
-              echo "BASH_ENV:"
-              cat $BASH_ENV
+  build_docs:
+    docker:
+      - image: cimg/python:3.10
+    resource_class: medium
+    steps:
+      - checkout
+      - run:
+          name: Set BASH_ENV
+          command: |
+            echo "set -e" >> $BASH_ENV
+            echo "export DISPLAY=:99" >> $BASH_ENV
+            echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
+            echo "BASH_ENV:"
+            cat $BASH_ENV
 
-        - run:
-            name: Merge with upstream
-            command: |
-              echo $(git log -1 --pretty=%B) | tee gitlog.txt
-              echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
-              if [[ $(cat merge.txt) != "" ]]; then
-                echo "Merging $(cat merge.txt)";
-                git remote add upstream https://github.com/torchdr/torchdr.git;
-                git pull --ff-only upstream "refs/pull/$(cat merge.txt)/merge";
-                git fetch upstream main;
-              fi
+      - run:
+          name: Merge with upstream
+          command: |
+            echo $(git log -1 --pretty=%B) | tee gitlog.txt
+            echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
+            if [[ $(cat merge.txt) != "" ]]; then
+              echo "Merging $(cat merge.txt)";
+              git remote add upstream https://github.com/torchdr/torchdr.git;
+              git pull --ff-only upstream "refs/pull/$(cat merge.txt)/merge";
+              git fetch upstream main;
+            fi
 
-        # Load our data
-        - restore_cache:
-            keys:
-              - data-cache-0
-              - pip-cache
+      # Load our data
+      - restore_cache:
+          keys:
+            - data-cache-0
+            - pip-cache
 
-        - run:
-            name: Install ffmpeg
-            command: |
-              sudo apt update 
-              sudo apt install ffmpeg
+      - run:
+          name: Install ffmpeg
+          command: |
+            sudo apt update
+            sudo apt install ffmpeg
 
-        - run:
-            name: Get Python running
-            command: |
-              python -m pip install --user --upgrade --progress-bar off pip
-              python -m pip install --user -e .[all]
-              python -m pip install --user .[doc]
-          # python -m pip install --user --upgrade --progress-bar off ipython "https://api.github.com/repos/sphinx-gallery/sphinx-gallery/zipball/master" memory_profiler
-        - save_cache:
-            key: pip-cache
-            paths:
-              - ~/.cache/pip
+      - run:
+          name: Get Python running
+          command: |
+            python -m pip install --user --upgrade --progress-bar off pip
+            python -m pip install --user -e .[all]
+            python -m pip install --user .[doc]
+        # python -m pip install --user --upgrade --progress-bar off ipython "https://api.github.com/repos/sphinx-gallery/sphinx-gallery/zipball/master" memory_profiler
+      - save_cache:
+          key: pip-cache
+          paths:
+            - ~/.cache/pip
 
+      # Look at what we have and fail early if there is some library conflict
+      - run:
+          name: Check installation
+          command: |
+            which python
+            python -c "import torchdr"
+            which sphinx-build
 
-        # Look at what we have and fail early if there is some library conflict
-        - run:
-            name: Check installation
-            command: |
-               which python
-               python -c "import torchdr"
-               which sphinx-build
+      # - run:
+      #     name: Correct link in release file
+      #     command: |
+      #       sed -i -r 's/PR #([[:digit:]]*)/\[PR #\1\]\(https:\/\/github.com\/torchdr\/torchdr\/pull\/\1\)/' RELEASES.md
+      #       sed -i -r 's/Issue #([[:digit:]]*)/\[Issue #\1\]\(https:\/\/github.com\/torchdr\/torchdr\/issues\/\1\)/' RELEASES.md
+      # Build docs
+      - run:
+          name: make html
+          command: |
+            cd docs;
+            make html;
+          no_output_timeout: 30m
 
-        # - run:
-        #     name: Correct link in release file
-        #     command: |
-        #       sed -i -r 's/PR #([[:digit:]]*)/\[PR #\1\]\(https:\/\/github.com\/torchdr\/torchdr\/pull\/\1\)/' RELEASES.md
-        #       sed -i -r 's/Issue #([[:digit:]]*)/\[Issue #\1\]\(https:\/\/github.com\/torchdr\/torchdr\/issues\/\1\)/' RELEASES.md
-        # Build docs
-        - run:
-            name: make html
-            command: |
-              cd docs;
-              make html;
-            no_output_timeout: 30m
+      # Save the outputs
+      - store_artifacts:
+          path: docs/build/html/
+          destination: dev
+      - persist_to_workspace:
+          root: docs/build
+          paths:
+            - html
 
-        # Save the outputs
-        - store_artifacts:
-            path: docs/build/html/
-            destination: dev
-        - persist_to_workspace:
-            root: docs/build
-            paths:
-              - html
-
-    deploy_main:
-      docker:
-        - image: cimg/python:3.10
-      steps:
-        - attach_workspace:
-            at: /tmp/build
-        - run:
-            name: Fetch docs
-            command: |
-              set -e
-              mkdir -p ~/.ssh
-              echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
-              chmod og= ~/.ssh/config
-              if [ ! -d ~/torchdr.github.io ]; then
-                git clone git@github.com:/torchdr/torchdr.github.io ~/torchdr.github.io --depth=1
-              fi
-        - run:
-            name: Deploy docs
-            command: |
-              set -e;
-              if [ "${CIRCLE_BRANCH}" == "main" ]; then
-                git config --global user.email "circle@torchdr.github.io";
-                git config --global user.name "Circle CI";
-                cd ~/torchdr.github.io;
-                git checkout main
-                git remote -v
-                git fetch origin
-                git reset --hard origin/main
-                git clean -xdf
-                echo "Deploying dev docs for ${CIRCLE_BRANCH}.";
-                cd dev
-                cp -a /tmp/build/html/* .;
-                touch .nojekyll;
-                git add -A;
-                git commit -m "CircleCI update of dev docs (${CIRCLE_BUILD_NUM}).";
-                git pull origin main;
-                git push origin main;
-              else
-                echo "No deployment (build: ${CIRCLE_BRANCH}).";
-              fi
-
-    deploy_tag:
-      docker:
-        - image: cimg/python:3.10
-      steps:
-        - attach_workspace:
-            at: /tmp/build
-        - run:
-            name: Fetch docs
-            command: |
-              set -e
-              mkdir -p ~/.ssh
-              echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
-              chmod og= ~/.ssh/config
-              if [ ! -d ~/torchdr.github.io ]; then
-                git clone git@github.com:/torchdr/torchdr.github.io ~/torchdr.github.io --depth=1
-              fi
-        - run:
-            name: Deploy docs
-            command: |
-              set -e;
+  deploy_main:
+    docker:
+      - image: cimg/python:3.10
+    steps:
+      - attach_workspace:
+          at: /tmp/build
+      - run:
+          name: Fetch docs
+          command: |
+            set -e
+            mkdir -p ~/.ssh
+            echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
+            chmod og= ~/.ssh/config
+            if [ ! -d ~/torchdr.github.io ]; then
+              git clone git@github.com:/torchdr/torchdr.github.io ~/torchdr.github.io --depth=1
+            fi
+      - run:
+          name: Deploy docs
+          command: |
+            set -e;
+            if [ "${CIRCLE_BRANCH}" == "main" ]; then
               git config --global user.email "circle@torchdr.github.io";
               git config --global user.name "Circle CI";
               cd ~/torchdr.github.io;
@@ -154,24 +113,62 @@ jobs:
               git reset --hard origin/main
               git clean -xdf
               echo "Deploying dev docs for ${CIRCLE_BRANCH}.";
+              cd dev
               cp -a /tmp/build/html/* .;
               touch .nojekyll;
               git add -A;
               git commit -m "CircleCI update of dev docs (${CIRCLE_BUILD_NUM}).";
               git pull origin main;
               git push origin main;
+            else
+              echo "No deployment (build: ${CIRCLE_BRANCH}).";
+            fi
 
+  deploy_tag:
+    docker:
+      - image: cimg/python:3.10
+    steps:
+      - attach_workspace:
+          at: /tmp/build
+      - run:
+          name: Fetch docs
+          command: |
+            set -e
+            mkdir -p ~/.ssh
+            echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config
+            chmod og= ~/.ssh/config
+            if [ ! -d ~/torchdr.github.io ]; then
+              git clone git@github.com:/torchdr/torchdr.github.io ~/torchdr.github.io --depth=1
+            fi
+      - run:
+          name: Deploy docs
+          command: |
+            set -e;
+            git config --global user.email "circle@torchdr.github.io";
+            git config --global user.name "Circle CI";
+            cd ~/torchdr.github.io;
+            git checkout main
+            git remote -v
+            git fetch origin
+            git reset --hard origin/main
+            git clean -xdf
+            echo "Deploying dev docs for ${CIRCLE_BRANCH}.";
+            cp -a /tmp/build/html/* .;
+            touch .nojekyll;
+            git add -A;
+            git commit -m "CircleCI update of dev docs (${CIRCLE_BUILD_NUM}).";
+            git pull origin main;
+            git push origin main;
 
 workflows:
   version: 2
 
   default:
-
     jobs:
       - build_docs:
           filters:
             tags:
-              only: /[0-9]+(\.[0-9]+)*$/  
+              only: /[0-9]+(\.[0-9]+)*$/
       - deploy_main:
           requires:
             - build_docs
